server.port=8099
spring.application.name=api-gateway

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins[0]=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins[1]=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins[2]=http://127.0.0.1:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

# Route 0: Registration Service
spring.cloud.gateway.routes[0].id=registration-service
spring.cloud.gateway.routes[0].uri=lb://REGISTRATION-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Route 1: Admission Service
spring.cloud.gateway.routes[1].id=admission-service
spring.cloud.gateway.routes[1].uri=lb://ADMISSION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/admissions/**

# Route 2: Student Enquire Service
spring.cloud.gateway.routes[2].id=student-enquire-service
spring.cloud.gateway.routes[2].uri=lb://STUDENT-ENQUIRE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/enquiries/**

# Route 3: Parent Enquiry Service
spring.cloud.gateway.routes[3].id=parent-enquiry-service
spring.cloud.gateway.routes[3].uri=lb://PARENT-ENQUIRY-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/parent-enquiries/**

# Route 4: Admin Enquiries Service
spring.cloud.gateway.routes[4].id=admin-enquiries-service
spring.cloud.gateway.routes[4].uri=lb://ADMIN-ENQUIRIES-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/admin/enquiries/**

# Route 5: Admin Admissions Service
spring.cloud.gateway.routes[5].id=admin-admissions-service
spring.cloud.gateway.routes[5].uri=lb://ADMIN-ADMISSIONS-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/admin/admissions/**

# Route 6: Teacher Enquiry Service
spring.cloud.gateway.routes[6].id=teacher-enquiry-service
spring.cloud.gateway.routes[6].uri=lb://TEACHER-ENQUIRY-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/teacher/enquiries/**

# Route 7: Staff Enquiry Service
spring.cloud.gateway.routes[7].id=staff-enquiry-service
spring.cloud.gateway.routes[7].uri=lb://STAFF-ENQUIRY-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/staff/enquiries/**

# Route 8: Student Portal Service
spring.cloud.gateway.routes[8].id=student-portal-service
spring.cloud.gateway.routes[8].uri=lb://STUDENT-PORTAL-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/student-portal/**

# Route 9: Teacher Portal Service
spring.cloud.gateway.routes[9].id=teacher-portal-service
spring.cloud.gateway.routes[9].uri=lb://TEACHER-PORTAL-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/teacher-portal/**

# Route 10: Staff Portal Service
spring.cloud.gateway.routes[10].id=staff-portal-service
spring.cloud.gateway.routes[10].uri=lb://STAFF-PORTAL-SERVICE
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/staff-portal/**

# Route 11: Staff Student Directory Service
spring.cloud.gateway.routes[11].id=staff-student-service
spring.cloud.gateway.routes[11].uri=lb://STAFF-STUDENT-SERVICE
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/staff-student/**

# Route 12: Teacher Attendance Service
spring.cloud.gateway.routes[12].id=teacher-attendance-service
spring.cloud.gateway.routes[12].uri=lb://TEACHER-ATTENDANCE-SERVICE
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/teacher-attendance/**

# Route 13: Student Schedule Service
spring.cloud.gateway.routes[13].id=student-schedule-service
spring.cloud.gateway.routes[13].uri=lb://STUDENT-SCHEDULE-SERVICE
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/student-schedule/**

# Route 14: Staff Examination Service
spring.cloud.gateway.routes[14].id=staff-examination-service
spring.cloud.gateway.routes[14].uri=lb://STAFF-EXAMINATION-SERVICE
spring.cloud.gateway.routes[14].predicates[0]=Path=/api/staff-examination/**

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost
